name: contoso-traders-playwright

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  run-playwright-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install dependencies
        run: npm ci
        working-directory: src/ContosoTraders.Ui.Website
      - name: install playwright browsers
        run: npx playwright install --with-deps
        working-directory: src/ContosoTraders.Ui.Website
      - name: run playwright tests
        run: npx playwright test
        working-directory: src/ContosoTraders.Ui.Website
      - name: upload playwright report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: src/ContosoTraders.Ui.Website/playwright-report/
          retention-days: 30
